version: "3.9"
services:
  web:
    build: . .
    command: 
      - python manage.py migrate
      - python manage.py runserver
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "GameProduct_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"