version: "3.9"
services:
  web:
    build: .
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
       POSTGRES_DB: "GameProduct_db"
       POSTGRES_USER: "postgres"
       POSTGRES_PASSWORD: "postgres"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "GameProduct_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"